from . import sale_order_type
from . import product_template
from . import res_partner
from . import product_category
from . import account_invoice
from . import account_invoice_line
from . import sale_make_invoice_advance
from . import sale_order_line
from . import sale_order
